---
- hosts: docker
  become: true

  tasks:
#  did not work... I need to learn more ansible
#  - name: add self to docker group if needed
#    command: if ! groups|grep docker > /dev/null 2>&1; then sudo usermod -aG docker ansadmin ; fi

  - name: remove current container
    command: docker rm -f simple-devops-container
    ignore_errors: yes

  - name: remove current container
    command: docker rmi 4art4/simple-devops-image:latest
    ignore_errors: yes

  - name: create container from new image
    command: docker run -d --name simple-devops-container -p 8080:8080 4art4/simple-devops-image:latest
