---
- hosts: ansible
  become: true

  tasks:
  - name: remove current image
    command: docker rmi thehackadmin/simple-devops-image simple-devops-image 4art4/simple-devops-image
    ignore_errors: yes

  - name: build docker image using war file
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /opt/docker

  - name: create docker tag
    command: docker tag simple-devops-image 4art4/simple-devops-image:latest

  - name: push container to docker hub
    command: docker push 4art4/simple-devops-image:latest
    
#  cannot have password in public git repo... moved to jenkins job
#  - name: login to docker hub
#    command: docker login -u thehackadmin
    
  - name: remove current image
    command: docker rmi simple-devops-image
    ignore_errors: yes
