---
- hosts: ansible
  become: false

  tasks:
  - name: remove current image
    command: docker rmi thehackadmin/simple-devops-image
    ignore_errors: yes

  - name: build docker image using war file
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /opt/docker

  - name: create docker tag
    command: docker tag simple-devops-image thehackadmin/simple-devops-image

  - name: push container to docker hub
    command: docker push thehackadmin/simple-devops-image
    
  - name: remove current image
    command: docker rmi simple-devops-image
    ignore_errors: yes
