---
- hosts: ansible
  become: false

  tasks:
  - name: remove current container
    command: docker rm -f simple-devops-container
    ignore_errors: yes

  - name: build docker image using war file
    command: docker build -t simple-devops-image .
    args:
      chdir: /opt/docker
  - name: create container from new image
    command: docker run -d --name simple-devops-container -p 8080:8080 simple-devops-image
